[package]
name = "dnd-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
serenity = "0.12"
serenity-commands = "0.8.0"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
